# Generated by Django 2.2.5 on 2019-09-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.PositiveIntegerField()),
                ('DonationType', models.CharField(max_length=250)),
            ],
        ),
    ]
