# Generated by Django 2.2.5 on 2019-09-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DonationType', models.CharField(max_length=50)),
                ('Quality', models.PositiveIntegerField()),
                ('Amount', models.PositiveIntegerField()),
                ('TotalAmount', models.PositiveIntegerField()),
            ],
        ),
    ]
